### ISSUE TITLE
Performance degradation on a long running network

### ISSUE THREAD

**Issue by askolesov** [exonum/exonum#1912]
**Description:**

We have a demo network of 4 nodes running in Aws. At the start, the network performs well, blocks are committed according to configured timeouts. After a couple of weeks, performance starts degrading. Intervals between blocks become about 30 seconds. Height of one of the nodes becomes much less than the height of others.

There is still a lot of RAM (>3 GB) and SSD (>10 GB) free space. Size of DB folder is about 4 GB.

The most interesting part is that restarting of all node processes helps to fix the issue. Not sure if the laggard node is able to catch up others, but other nodes start working as at the beginning.

It would be great to know how to fix this issue or at least where to look at and how to efficiently debug such cases.

Thanks!

**Configuration:**

Network size: 4 nodes
Node OS: Ubuntu 18.04
Exonum version: 1.0.0
Consensus configuration:
```toml
[consensus]
first_round_timeout = 3000
max_message_len = 1048576
max_propose_timeout = 2000
min_propose_timeout = 1000
peers_timeout = 10000
propose_timeout_threshold = 50
status_timeout = 5000
txs_block_limit = 1000
```

**Steps to reproduce:**

1. Strart a network of 4 nodes in the same region in AWS
2. Wait for a cople of weeks

**Result:**

Network performance is degraded. Intervals between blocks become about 30 seconds.

**Expected result:**

Network performance is not degraded.
